#!/usr/bin/env node

var fs = require('fs')
var pkg = require('../package.json')
var ometa = require('../lib/ometa-js')
var parser = require('../src/jedi')
var util = require('../src/util')

var program = require('commander')

program.
	version(pkg.version).
	option('-p, --parse', '解析指定文件').
	parse(process.argv)

if (program.args.length > 0) {

	var srcPath = program.args[0]
	if (!fs.existsSync(srcPath)) {
		srcPath += '.jedi'
		if (!fs.existsSync(srcPath)) {
			console.error('文件' + srcPath + '不存在')
			throw new Error('Cannot find file: ' + srcPath)
		}
	}

	var tree = parser.Parser.match(srcPath, 'load')
	//util.dir(tree)

} else {
	program.help()
}

