#!/usr/bin/env node

var fs = require('fs'), path = require('path')
var pkg = require('../package.json')
var jedi = require('../src')

var program = require('commander')

program.
	version(pkg.version).
	option('--php', '编译为PHP').
	//option('-e, --error-handler [type]', '指定错误处理器', 'html').
	option('-w, --watch', '当指定文件的内容变化时自动重新编译').
	option('-s, --service', '启动编译服务').
	option('-p, --port <n>', '编译服务端口', parseInt).
	parse(process.argv)

if (program.service) {

	jedi.service({
		base: program.args[0] || process.cwd(),
		port: program.port || 1337
	})

} else if (program.args.length > 0) {

	var srcPath = path.resolve(program.args[0])
	if (!fs.existsSync(srcPath)) {
		srcPath += '.jedi'
		if (!fs.existsSync(srcPath)) {
			console.error('文件' + srcPath + '不存在')
			throw new Error('file not exists: ' + srcPath)
		}
	}
	var destPath = program.args[1] || srcPath.replace(/(\.jedi)?$/, '.php')

	if (program.watch) jedi.watch(srcPath, destPath)
	else jedi.transpile(srcPath, destPath)

} else {
	program.help()
}

